# The input bucket
OUT_S3_BUCKET_LINGPROC ?= 40-processed-data-sandbox
  $(call log.debug, OUT_S3_BUCKET_LINGPROC)

OUT_PROCESS_LABEL_LINGPROC ?= lingproc
  $(call log.debug, OUT_PROCESS_LABEL_LINGPROC)

OUT_PROCESS_SUBTYPE_LABEL_LINGPROC ?=
  $(call log.debug, OUT_PROCESS_SUBTYPE_LABEL_LINGPROC)
  
OUT_TASK_LINGPROC ?= pos
  $(call log.debug, OUT_TASK_LINGPROC)

OUT_MODEL_ID_LINGPROC ?= spacy_v3.6.0-multilingual
  $(call log.debug, OUT_MODEL_ID_LINGPROC)

OUT_RUN_VERSION_LINGPROC ?= v2-0-0
  $(call log.debug, OUT_RUN_VERSION_LINGPROC)
  
OUT_RUN_ID_LINGPROC ?= $(OUT_PROCESS_LABEL_LINGPROC)-$(OUT_TASK_LINGPROC)-$(OUT_MODEL_ID_LINGPROC)_$(OUT_RUN_VERSION_LINGPROC)
  $(call log.debug, OUT_RUN_ID_LINGPROC)
  
# The s3 input path
OUT_S3_PATH_LINGPROC := s3://$(OUT_S3_BUCKET_LINGPROC)/$(OUT_PROCESS_LABEL_LINGPROC)$(OUT_PROCESS_SUBTYPE_LABEL_LINGPROC)/$(OUT_RUN_ID_LINGPROC)/$(NEWSPAPER)
  $(call log.debug, OUT_S3_PATH_LINGPROC)

# The local path in BUILD_DIR
OUT_LOCAL_PATH_LINGPROC := $(BUILD_DIR)/$(OUT_S3_BUCKET_LINGPROC)/$(OUT_PROCESS_LABEL_LINGPROC)$(OUT_PROCESS_SUBTYPE_LABEL_LINGPROC)/$(OUT_RUN_ID_LINGPROC)/$(NEWSPAPER)
  $(call log.debug, OUT_LOCAL_PATH_LINGPROC)
