# The input bucket
S3_BUCKET_LINGPROC ?= 40-processed-data-sandbox
  $(call log.debug, S3_BUCKET_LINGPROC)

PROCESS_LABEL_LINGPROC ?= lingproc
  $(call log.debug, PROCESS_LABEL_LINGPROC)

PROCESS_SUBTYPE_LABEL_LINGPROC ?=
  $(call log.debug, PROCESS_SUBTYPE_LABEL_LINGPROC)
  
TASK_LINGPROC ?= pos
  $(call log.debug, TASK_LINGPROC)

MODEL_ID_LINGPROC ?= spacy_v3.6.0-multilingual
  $(call log.debug, MODEL_ID_LINGPROC)

RUN_VERSION_LINGPROC ?= v2-0-0
  $(call log.debug, RUN_VERSION_LINGPROC)
  
RUN_ID_LINGPROC ?= $(PROCESS_LABEL_LINGPROC)-$(TASK_LINGPROC)-$(MODEL_ID_LINGPROC)_$(RUN_VERSION_LINGPROC)
  $(call log.debug, RUN_ID_LINGPROC)
  
# The s3 input path
S3_PATH_LINGPROC := s3://$(S3_BUCKET_LINGPROC)/$(PROCESS_LABEL_LINGPROC)$(PROCESS_SUBTYPE_LABEL_LINGPROC)/$(RUN_ID_LINGPROC)/$(NEWSPAPER)
  $(call log.debug, S3_PATH_LINGPROC)

# The local path in BUILD_DIR
LOCAL_PATH_LINGPROC := $(BUILD_DIR)/$(S3_BUCKET_LINGPROC)/$(PROCESS_LABEL_LINGPROC)$(PROCESS_SUBTYPE_LABEL_LINGPROC)/$(RUN_ID_LINGPROC)/$(NEWSPAPER)
  $(call log.debug, LOCAL_PATH_LINGPROC)
